"""Generate ``docs/data-contract.md`` from canonical schemas + module docstring.

Two run modes:

* (no flag): write ``docs/data-contract.md``. Idempotent given
  ``canonical.py``.
* ``--check``: render in-memory, compare to the file on disk byte-for-byte.
  Exits 0 if equal, 1 with a diff snippet on stderr if not. CI uses
  ``--check`` to gate drift.

The generated file carries an autogeneration warning at the top. Adapter
routing rules are NOT included here — the file is canonical-only and
points at ``ehr_simulator/ingestion/{adapter}.py`` module docstrings for
adapter-specific behavior.
"""

from __future__ import annotations

import argparse
import difflib
import sys
import textwrap
from pathlib import Path

import pandera.pandas as pa

from ehr_simulator.ingestion import canonical
from ehr_simulator.ingestion.canonical import SCHEMAS, CanonicalShape

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "data-contract.md"

_AUTOGEN_WARNING = (
    "<!-- This file is generated by scripts/gen_data_contract.py — do not edit by hand. -->"
)


def _format_check(check: pa.Check) -> str:
    name = getattr(check, "name", None) or check.__class__.__name__
    stats = getattr(check, "statistics", None)
    if stats:
        parts = [f"{k}={v!r}" for k, v in stats.items() if v is not None]
        if parts:
            return f"{name}({', '.join(parts)})"
    err = getattr(check, "error", None)
    if err:
        return f"{name} — {err}"
    return name


def _render_shape_section(shape: CanonicalShape) -> str:
    schema = SCHEMAS[shape]
    title = shape.value.upper()
    lines: list[str] = [f"## `{title}`", ""]

    lines.append("| column | dtype | nullable | constraints |")
    lines.append("|---|---|---|---|")
    for name, column in schema.columns.items():
        dtype_str = str(column.dtype)
        nullable = "yes" if column.nullable else "no"
        checks = column.checks or []
        check_strs = [_format_check(c) for c in checks]
        constraints = "; ".join(check_strs) if check_strs else "—"
        lines.append(f"| `{name}` | `{dtype_str}` | {nullable} | {constraints} |")
    lines.append("")

    if schema.unique:
        unique_cols = ", ".join(f"`{c}`" for c in schema.unique)
        lines.append(f"**Uniqueness:** {unique_cols}.")
        lines.append("")

    schema_checks = list(schema.checks or [])
    if schema_checks:
        lines.append("**Schema-level checks:**")
        for check in schema_checks:
            lines.append(f"- {_format_check(check)}")
        lines.append("")

    return "\n".join(lines)


def render_contract() -> str:
    overview = textwrap.dedent(canonical.__doc__ or "").strip()
    sections = [_render_shape_section(shape) for shape in CanonicalShape]
    body = "\n".join(sections).rstrip()
    closing = (
        "Adapter-specific routing rules: see "
        "`ehr_simulator/ingestion/{adapter}.py` module docstring "
        "(currently: `synthetic.py`, `geneva.py`, `mimic.py`)."
    )
    parts = [
        "# Canonical data contract",
        "",
        _AUTOGEN_WARNING,
        "",
        overview,
        "",
        body,
        "",
        closing,
        "",
    ]
    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare generated content to docs/data-contract.md; exit 1 on drift",
    )
    args = parser.parse_args(argv)

    rendered = render_contract()
    if args.check:
        if not OUTPUT_PATH.is_file():
            print(f"{OUTPUT_PATH} does not exist; run without --check first", file=sys.stderr)
            return 1
        on_disk = OUTPUT_PATH.read_text(encoding="utf-8")
        if on_disk == rendered:
            return 0
        diff = difflib.unified_diff(
            on_disk.splitlines(keepends=True),
            rendered.splitlines(keepends=True),
            fromfile="docs/data-contract.md",
            tofile="generated",
            n=3,
        )
        sys.stderr.writelines(diff)
        print(
            "\nfix: uv run python scripts/gen_data_contract.py (then commit the regenerated file)",
            file=sys.stderr,
        )
        return 1

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
